services:
  rainfrog-postgres:
    container_name: rainfrog-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "rainfrog"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./dev/pg_init.sql:/docker-entrypoint-initdb.d/00_init.sql
  rainfrog-mysql:
    container_name: rainfrog-mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "rainfrog"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./dev/mysql_init.sql:/docker-entrypoint-initdb.d/schema.sql

  rainfrog-oracle:
    container_name: rainfrog-oracle
    image: gvenzl/oracle-xe:21.3.0
    environment:
      ORACLE_PASSWORD: password
      APP_USER: rainfrog
      APP_USER_PASSWORD: password
      ORACLE_DATABASE: rainfrog
    ports:
      - "${ORACLE_PORT}:1521"
