services:
  rainfrog-postgres:
    container_name: rainfrog-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "rainfrog"
    ports:
      - "5432:5432"
    volumes:
      - ./dev/pg_init.sql:/docker-entrypoint-initdb.d/00_init.sql
  rainfrog-mysql:
    container_name: rainfrog-mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "rainfrog"
    ports:
      - "3306:3306"
    volumes:
      - ./dev/mysql_init.sql:/docker-entrypoint-initdb.d/schema.sql

  rainfrog-oracle:
    image: oriolrt/oracle-23ai
    container_name: oracle23ai
    environment:
      - ORACLE_PWD=password
    ports:
      - "1521:1521"  # Oracle Database listener
      - "5500:5500"  # Oracle Enterprise Manager (OEM) Express
      - "2222:22"    # SSH access
    # tty: true        # Equivalent to the `-t` option in `docker run`
    # stdin_open: true # Equivalent to the `-i` option in `docker run`
